"""Tests for AI Service, Provider Abstraction, and AI endpoints."""

import pytest
from fastapi.testclient import TestClient

from app.config import Settings
from app.main import app
from app.models.requests import AIAnalysisRequest, AIOperation
from app.routes.ai import get_ai_service
from app.services.ai_service import AIService
from app.services.providers.openai_provider import (
    AIProviderConfigurationError,
    AIProviderExecutionError,
    OpenAIProvider,
)
from tests.conftest import MockAIProvider


def test_analyze_project_summary_success(
    client: TestClient,
    sample_request: AIAnalysisRequest,
) -> None:
    """POST /ai/analyze returns 200 and structured response for PROJECT_SUMMARY."""
    payload = sample_request.model_dump(mode="json")
    response = client.post("/ai/analyze", json=payload)
    assert response.status_code == 200

    data = response.json()
    assert data["request_id"] == "req-test-uuid-9999"
    assert data["operation"] == "PROJECT_SUMMARY"
    assert "summary" in data
    assert isinstance(data["recommendations"], list)
    assert len(data["recommendations"]) == 2
    assert data["recommendations"][0]["priority"] == "CRITICAL"
    assert data["recommendations"][0]["category"] == "RISK_MITIGATION"


def test_analyze_task_summary_success(
    client: TestClient,
    sample_request: AIAnalysisRequest,
) -> None:
    """POST /ai/analyze executes TASK_SUMMARY operation successfully."""
    payload = sample_request.model_dump(mode="json")
    payload["operation"] = "TASK_SUMMARY"
    response = client.post("/ai/analyze", json=payload)
    assert response.status_code == 200

    data = response.json()
    assert data["operation"] == "TASK_SUMMARY"


def test_analyze_project_insight_success(
    client: TestClient,
    sample_request: AIAnalysisRequest,
) -> None:
    """POST /ai/analyze executes PROJECT_INSIGHT operation successfully."""
    payload = sample_request.model_dump(mode="json")
    payload["operation"] = "PROJECT_INSIGHT"
    response = client.post("/ai/analyze", json=payload)
    assert response.status_code == 200

    data = response.json()
    assert data["operation"] == "PROJECT_INSIGHT"


def test_request_id_autogenerated_when_omitted(
    client: TestClient,
    sample_request: AIAnalysisRequest,
) -> None:
    """If caller omits request_id, service automatically generates a UUID."""
    payload = sample_request.model_dump(mode="json")
    payload["request_id"] = None

    response = client.post("/ai/analyze", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["request_id"] is not None
    assert len(data["request_id"]) > 10


@pytest.mark.asyncio
async def test_ai_service_direct_unit(sample_request: AIAnalysisRequest) -> None:
    """Direct unit testing of AIService without HTTP transport layer."""
    mock = MockAIProvider()
    service = AIService(provider=mock)

    result = await service.analyze(sample_request)
    assert result.request_id == "req-test-uuid-9999"
    assert result.operation == AIOperation.PROJECT_SUMMARY
    assert len(result.recommendations) == 2
    assert mock.last_request is not None
    assert mock.last_request["operation"] == AIOperation.PROJECT_SUMMARY


def test_provider_configuration_error_returns_503(sample_request: AIAnalysisRequest) -> None:
    """Provider configuration failure returns 503 with standardized error code."""
    failing_provider = MockAIProvider(
        fail_with=AIProviderConfigurationError("OpenAI API key is missing")
    )
    app.dependency_overrides[get_ai_service] = lambda: AIService(provider=failing_provider)

    with TestClient(app) as test_client:
        payload = sample_request.model_dump(mode="json")
        response = test_client.post("/ai/analyze", json=payload)
        assert response.status_code == 503
        data = response.json()
        assert data["success"] is False
        assert data["error"]["code"] == "AI_PROVIDER_NOT_CONFIGURED"
        assert "not configured" in data["error"]["message"]

    app.dependency_overrides.clear()


def test_provider_execution_error_returns_502(sample_request: AIAnalysisRequest) -> None:
    """Upstream provider error returns 502 with sanitized message."""
    failing_provider = MockAIProvider(
        fail_with=AIProviderExecutionError("Rate limit reached on upstream AI provider")
    )
    app.dependency_overrides[get_ai_service] = lambda: AIService(provider=failing_provider)

    with TestClient(app) as test_client:
        payload = sample_request.model_dump(mode="json")
        response = test_client.post("/ai/analyze", json=payload)
        assert response.status_code == 502
        data = response.json()
        assert data["success"] is False
        assert data["error"]["code"] == "AI_PROVIDER_ERROR"

    app.dependency_overrides.clear()


def test_unexpected_error_returns_500_without_leak(sample_request: AIAnalysisRequest) -> None:
    """Unexpected exception returns 500 and prevents leaking internal stack trace."""
    failing_provider = MockAIProvider(
        fail_with=RuntimeError("internal database memory explosion sk-1234567890abcdef")
    )
    app.dependency_overrides[get_ai_service] = lambda: AIService(provider=failing_provider)

    with TestClient(app) as test_client:
        payload = sample_request.model_dump(mode="json")
        response = test_client.post("/ai/analyze", json=payload)
        assert response.status_code == 500
        data = response.json()
        assert data["success"] is False
        assert data["error"]["code"] == "AI_INTERNAL_ERROR"
        assert "sk-1234567890abcdef" not in response.text

    app.dependency_overrides.clear()


def test_openai_provider_missing_key_raises_config_error() -> None:
    """OpenAIProvider raises AIProviderConfigurationError when api_key is None or empty."""
    settings = Settings(openai_api_key=None)
    provider = OpenAIProvider(settings)

    with pytest.raises(AIProviderConfigurationError) as exc:
        provider._get_client()
    assert "OpenAI API key is not configured" in str(exc.value)


def test_openai_provider_prompt_builders(sample_request: AIAnalysisRequest) -> None:
    """OpenAIProvider correctly builds system and user context strings."""
    settings = Settings(openai_api_key="sk-test-key")
    provider = OpenAIProvider(settings)

    sys_prompt = provider._build_system_prompt(AIOperation.PROJECT_SUMMARY)
    assert "Project Operations AI" in sys_prompt
    assert "JSON object strictly matching this schema" in sys_prompt

    user_content = provider._build_user_content(
        sample_request.context,
        sample_request.user_prompt,
    )
    assert "Alpha Core Platform" in user_content
    assert "Total Active Tasks: 25" in user_content
    assert "ALPHA-101" in user_content
    assert "Provide an overview of potential bottlenecks." in user_content
